# Plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Change the status bar background and foreground colors to gray
set -g status-bg colour241      # Medium gray background
set -g status-fg white          # White foreground

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Copy directory in new session
bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind "'" split-window -v -c "#{pane_current_path}"

set -g mouse on
set -g history-limit 50000
